version: "3"

services:
   devprod:
      image: devprod:latest
      container_name: devprod
      environment:
        API_HOST: 192.168.224.142
        API_PORT: 8001
        API_PREFIX: /api
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8000:80"

















